/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Album {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'isShared' : boolean,
  'photos' : Array<Photo>,
}
export interface Amenity {
  'name' : string,
  'description' : [] | [string],
  'category' : AmenityCategory,
}
export type AmenityCategory = { 'transportation' : null } |
  { 'safetyAndSecurity' : null } |
  { 'entertainment' : null } |
  { 'roomFeatures' : null } |
  { 'recreationalFacilities' : null } |
  { 'businessServices' : null } |
  { 'petFriendly' : null } |
  { 'accessibilityFeatures' : null } |
  { 'technology' : null } |
  { 'diningOptions' : null } |
  { 'hotelServices' : null } |
  { 'hospitalityServices' : null } |
  { 'wellnessAndSpa' : null };
export interface Bundle {
  'ticket' : Ticket,
  'hotel' : Hotel,
  'roomType' : RoomType,
}
export interface BundleInput {
  'ticket' : Ticket,
  'hotel' : Hotel,
  'roomType' : RoomType,
}
export interface ComparisonInput {
  'ticketSources' : Array<Ticket>,
  'event' : string,
  'userChoice' : [] | [BundleInput],
  'vipPackageOptions' : Array<VIPPackage>,
  'hotels' : Array<Hotel>,
  'travelWindow' : TravelWindow,
}
export type ExternalBlob = Uint8Array;
export interface FriendEntry {
  'id' : bigint,
  'principal' : Principal,
  'name' : [] | [string],
  'isConfirmed' : boolean,
}
export interface GeoLocation { 'latitude' : number, 'longitude' : number }
export interface Group {
  'id' : bigint,
  'creator' : Principal,
  'members' : Array<GroupMember>,
  'comparisonId' : [] | [bigint],
  'messages' : Array<Message>,
  'createdAt' : Time,
  'lastUpdate' : Time,
  'groupName' : string,
}
export interface GroupMember {
  'id' : bigint,
  'userName' : string,
  'principal' : Principal,
  'isConfirmed' : boolean,
}
export interface Hotel {
  'roomTypes' : Array<RoomType>,
  'starRating' : [] | [number],
  'country' : string,
  'reviews' : [] | [number],
  'imageUrls' : [] | [Array<string>],
  'city' : string,
  'name' : string,
  'checkInTime' : [] | [string],
  'amenities' : Array<Amenity>,
  'state' : [] | [string],
  'address' : string,
  'prices' : [] | [PriceRange],
  'brand' : [] | [string],
  'checkOutTime' : [] | [string],
  'location' : [] | [GeoLocation],
}
export interface LegalInfo { 'legalName' : string }
export interface Message {
  'id' : bigint,
  'content' : string,
  'author' : [] | [GroupMember],
  'timestamp' : Time,
}
export interface NewMessage {
  'content' : string,
  'author' : [] | [GroupMember],
}
export interface Photo {
  'id' : bigint,
  'externalBlob' : ExternalBlob,
  'createdAt' : Time,
  'createdBy' : Principal,
  'tags' : Array<PhotoTag>,
  'description' : string,
  'imageUrl' : string,
}
export interface PhotoInput {
  'externalBlob' : ExternalBlob,
  'tags' : Array<PhotoTag>,
  'description' : string,
  'imageUrl' : string,
}
export interface PhotoTag {
  'principal' : Principal,
  'displayName' : string,
  'position' : [number, number],
}
export interface PriceRange {
  'maxPrice' : number,
  'currency' : string,
  'minPrice' : number,
  'rateType' : PriceType,
}
export type PriceType = { 'perNight' : null } |
  { 'perWeek' : null } |
  { 'perMonth' : null };
export interface RoomType {
  'bedType' : [] | [string],
  'occupancy' : [] | [bigint],
  'views' : [] | [string],
  'cancellationPolicy' : [] | [string],
  'name' : string,
  'size' : [] | [bigint],
  'description' : [] | [string],
  'amenities' : Array<Amenity>,
  'price' : number,
}
export interface Ticket {
  'id' : bigint,
  'name' : string,
  'type' : TicketType,
  'available' : boolean,
  'currency' : string,
  'price' : number,
}
export type TicketType = { 'vip' : null } |
  { 'standard' : null };
export type Time = bigint;
export interface TravelWindow { 'checkIn' : Time, 'checkOut' : Time }
export interface TripComparison {
  'id' : bigint,
  'userId' : Principal,
  'createdAt' : Time,
  'upgradeAlternatives' : Array<Bundle>,
  'ticketSources' : Array<Ticket>,
  'event' : string,
  'userChoice' : [] | [Bundle],
  'vipPackageOptions' : Array<VIPPackage>,
  'hotels' : Array<Hotel>,
  'travelWindow' : TravelWindow,
  'foundVIPPackage' : boolean,
}
export interface UserProfile {
  'publicScreenName' : string,
  'parentPermissionConfirmed' : boolean,
  'friends' : Array<FriendEntry>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VIPPackage {
  'id' : bigint,
  'exclusivePerks' : [] | [string],
  'name' : string,
  'inclusions' : Array<string>,
  'currency' : string,
  'price' : number,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFriendRequest' : ActorMethod<[FriendEntry], undefined>,
  'addGroupMessage' : ActorMethod<[bigint, NewMessage], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlbum' : ActorMethod<[string], Album>,
  'createGroup' : ActorMethod<
    [string, Principal, Array<GroupMember>, [] | [bigint]],
    Group
  >,
  'createTripComparison' : ActorMethod<
    [ComparisonInput, boolean],
    TripComparison
  >,
  'deleteAlbum' : ActorMethod<[bigint], undefined>,
  'deleteComparison' : ActorMethod<[bigint], undefined>,
  'deletePhotoFromAlbum' : ActorMethod<[bigint, bigint], undefined>,
  'getAlbum' : ActorMethod<[bigint], [] | [Album]>,
  'getAllAlbums' : ActorMethod<[Principal], Array<Album>>,
  'getAllGroups' : ActorMethod<[], Array<Group>>,
  'getAllUserComparisons' : ActorMethod<[Principal], Array<TripComparison>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGroup' : ActorMethod<[bigint], [] | [Group]>,
  'getLegalInfo' : ActorMethod<[], [] | [LegalInfo]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'leaveGroup' : ActorMethod<[bigint], undefined>,
  'removeFriend' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLegalInfo' : ActorMethod<[LegalInfo], undefined>,
  'setParentPermissionStatus' : ActorMethod<[boolean], undefined>,
  'uploadPhotoToAlbum' : ActorMethod<[bigint, PhotoInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];