/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const FriendEntry = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'name' : IDL.Opt(IDL.Text),
  'isConfirmed' : IDL.Bool,
});
export const GroupMember = IDL.Record({
  'id' : IDL.Nat,
  'userName' : IDL.Text,
  'principal' : IDL.Principal,
  'isConfirmed' : IDL.Bool,
});
export const NewMessage = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Opt(GroupMember),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const PhotoTag = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'position' : IDL.Tuple(IDL.Float64, IDL.Float64),
});
export const Photo = IDL.Record({
  'id' : IDL.Nat,
  'externalBlob' : ExternalBlob,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'tags' : IDL.Vec(PhotoTag),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Album = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'isShared' : IDL.Bool,
  'photos' : IDL.Vec(Photo),
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Opt(GroupMember),
  'timestamp' : Time,
});
export const Group = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'members' : IDL.Vec(GroupMember),
  'comparisonId' : IDL.Opt(IDL.Nat),
  'messages' : IDL.Vec(Message),
  'createdAt' : Time,
  'lastUpdate' : Time,
  'groupName' : IDL.Text,
});
export const TicketType = IDL.Variant({
  'vip' : IDL.Null,
  'standard' : IDL.Null,
});
export const Ticket = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'type' : TicketType,
  'available' : IDL.Bool,
  'currency' : IDL.Text,
  'price' : IDL.Float64,
});
export const AmenityCategory = IDL.Variant({
  'transportation' : IDL.Null,
  'safetyAndSecurity' : IDL.Null,
  'entertainment' : IDL.Null,
  'roomFeatures' : IDL.Null,
  'recreationalFacilities' : IDL.Null,
  'businessServices' : IDL.Null,
  'petFriendly' : IDL.Null,
  'accessibilityFeatures' : IDL.Null,
  'technology' : IDL.Null,
  'diningOptions' : IDL.Null,
  'hotelServices' : IDL.Null,
  'hospitalityServices' : IDL.Null,
  'wellnessAndSpa' : IDL.Null,
});
export const Amenity = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'category' : AmenityCategory,
});
export const RoomType = IDL.Record({
  'bedType' : IDL.Opt(IDL.Text),
  'occupancy' : IDL.Opt(IDL.Nat),
  'views' : IDL.Opt(IDL.Text),
  'cancellationPolicy' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'size' : IDL.Opt(IDL.Nat),
  'description' : IDL.Opt(IDL.Text),
  'amenities' : IDL.Vec(Amenity),
  'price' : IDL.Float64,
});
export const PriceType = IDL.Variant({
  'perNight' : IDL.Null,
  'perWeek' : IDL.Null,
  'perMonth' : IDL.Null,
});
export const PriceRange = IDL.Record({
  'maxPrice' : IDL.Float64,
  'currency' : IDL.Text,
  'minPrice' : IDL.Float64,
  'rateType' : PriceType,
});
export const GeoLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Hotel = IDL.Record({
  'roomTypes' : IDL.Vec(RoomType),
  'starRating' : IDL.Opt(IDL.Float64),
  'country' : IDL.Text,
  'reviews' : IDL.Opt(IDL.Float64),
  'imageUrls' : IDL.Opt(IDL.Vec(IDL.Text)),
  'city' : IDL.Text,
  'name' : IDL.Text,
  'checkInTime' : IDL.Opt(IDL.Text),
  'amenities' : IDL.Vec(Amenity),
  'state' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'prices' : IDL.Opt(PriceRange),
  'brand' : IDL.Opt(IDL.Text),
  'checkOutTime' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(GeoLocation),
});
export const BundleInput = IDL.Record({
  'ticket' : Ticket,
  'hotel' : Hotel,
  'roomType' : RoomType,
});
export const VIPPackage = IDL.Record({
  'id' : IDL.Nat,
  'exclusivePerks' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'inclusions' : IDL.Vec(IDL.Text),
  'currency' : IDL.Text,
  'price' : IDL.Float64,
});
export const TravelWindow = IDL.Record({ 'checkIn' : Time, 'checkOut' : Time });
export const ComparisonInput = IDL.Record({
  'ticketSources' : IDL.Vec(Ticket),
  'event' : IDL.Text,
  'userChoice' : IDL.Opt(BundleInput),
  'vipPackageOptions' : IDL.Vec(VIPPackage),
  'hotels' : IDL.Vec(Hotel),
  'travelWindow' : TravelWindow,
});
export const Bundle = IDL.Record({
  'ticket' : Ticket,
  'hotel' : Hotel,
  'roomType' : RoomType,
});
export const TripComparison = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'upgradeAlternatives' : IDL.Vec(Bundle),
  'ticketSources' : IDL.Vec(Ticket),
  'event' : IDL.Text,
  'userChoice' : IDL.Opt(Bundle),
  'vipPackageOptions' : IDL.Vec(VIPPackage),
  'hotels' : IDL.Vec(Hotel),
  'travelWindow' : TravelWindow,
  'foundVIPPackage' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'parentPermissionConfirmed' : IDL.Bool,
  'friends' : IDL.Vec(FriendEntry),
});
export const PhotoInput = IDL.Record({
  'externalBlob' : ExternalBlob,
  'tags' : IDL.Vec(PhotoTag),
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFriendRequest' : IDL.Func([FriendEntry], [], []),
  'addGroupMessage' : IDL.Func([IDL.Nat, NewMessage], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlbum' : IDL.Func([IDL.Text], [Album], []),
  'createGroup' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Vec(GroupMember), IDL.Opt(IDL.Nat)],
      [Group],
      [],
    ),
  'createTripComparison' : IDL.Func(
      [ComparisonInput, IDL.Bool],
      [TripComparison],
      [],
    ),
  'deleteAlbum' : IDL.Func([IDL.Nat], [], []),
  'deleteComparison' : IDL.Func([IDL.Nat], [], []),
  'deletePhotoFromAlbum' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getAlbum' : IDL.Func([IDL.Nat], [IDL.Opt(Album)], ['query']),
  'getAllAlbums' : IDL.Func([IDL.Principal], [IDL.Vec(Album)], ['query']),
  'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getAllUserComparisons' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TripComparison)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGroup' : IDL.Func([IDL.Nat], [IDL.Opt(Group)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveGroup' : IDL.Func([IDL.Nat], [], []),
  'removeFriend' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setParentPermissionStatus' : IDL.Func([IDL.Bool], [], []),
  'uploadPhotoToAlbum' : IDL.Func([IDL.Nat, PhotoInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const FriendEntry = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'name' : IDL.Opt(IDL.Text),
    'isConfirmed' : IDL.Bool,
  });
  const GroupMember = IDL.Record({
    'id' : IDL.Nat,
    'userName' : IDL.Text,
    'principal' : IDL.Principal,
    'isConfirmed' : IDL.Bool,
  });
  const NewMessage = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Opt(GroupMember),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const PhotoTag = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'position' : IDL.Tuple(IDL.Float64, IDL.Float64),
  });
  const Photo = IDL.Record({
    'id' : IDL.Nat,
    'externalBlob' : ExternalBlob,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'tags' : IDL.Vec(PhotoTag),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Album = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'isShared' : IDL.Bool,
    'photos' : IDL.Vec(Photo),
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Opt(GroupMember),
    'timestamp' : Time,
  });
  const Group = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'members' : IDL.Vec(GroupMember),
    'comparisonId' : IDL.Opt(IDL.Nat),
    'messages' : IDL.Vec(Message),
    'createdAt' : Time,
    'lastUpdate' : Time,
    'groupName' : IDL.Text,
  });
  const TicketType = IDL.Variant({ 'vip' : IDL.Null, 'standard' : IDL.Null });
  const Ticket = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'type' : TicketType,
    'available' : IDL.Bool,
    'currency' : IDL.Text,
    'price' : IDL.Float64,
  });
  const AmenityCategory = IDL.Variant({
    'transportation' : IDL.Null,
    'safetyAndSecurity' : IDL.Null,
    'entertainment' : IDL.Null,
    'roomFeatures' : IDL.Null,
    'recreationalFacilities' : IDL.Null,
    'businessServices' : IDL.Null,
    'petFriendly' : IDL.Null,
    'accessibilityFeatures' : IDL.Null,
    'technology' : IDL.Null,
    'diningOptions' : IDL.Null,
    'hotelServices' : IDL.Null,
    'hospitalityServices' : IDL.Null,
    'wellnessAndSpa' : IDL.Null,
  });
  const Amenity = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'category' : AmenityCategory,
  });
  const RoomType = IDL.Record({
    'bedType' : IDL.Opt(IDL.Text),
    'occupancy' : IDL.Opt(IDL.Nat),
    'views' : IDL.Opt(IDL.Text),
    'cancellationPolicy' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'size' : IDL.Opt(IDL.Nat),
    'description' : IDL.Opt(IDL.Text),
    'amenities' : IDL.Vec(Amenity),
    'price' : IDL.Float64,
  });
  const PriceType = IDL.Variant({
    'perNight' : IDL.Null,
    'perWeek' : IDL.Null,
    'perMonth' : IDL.Null,
  });
  const PriceRange = IDL.Record({
    'maxPrice' : IDL.Float64,
    'currency' : IDL.Text,
    'minPrice' : IDL.Float64,
    'rateType' : PriceType,
  });
  const GeoLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Hotel = IDL.Record({
    'roomTypes' : IDL.Vec(RoomType),
    'starRating' : IDL.Opt(IDL.Float64),
    'country' : IDL.Text,
    'reviews' : IDL.Opt(IDL.Float64),
    'imageUrls' : IDL.Opt(IDL.Vec(IDL.Text)),
    'city' : IDL.Text,
    'name' : IDL.Text,
    'checkInTime' : IDL.Opt(IDL.Text),
    'amenities' : IDL.Vec(Amenity),
    'state' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'prices' : IDL.Opt(PriceRange),
    'brand' : IDL.Opt(IDL.Text),
    'checkOutTime' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(GeoLocation),
  });
  const BundleInput = IDL.Record({
    'ticket' : Ticket,
    'hotel' : Hotel,
    'roomType' : RoomType,
  });
  const VIPPackage = IDL.Record({
    'id' : IDL.Nat,
    'exclusivePerks' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'inclusions' : IDL.Vec(IDL.Text),
    'currency' : IDL.Text,
    'price' : IDL.Float64,
  });
  const TravelWindow = IDL.Record({ 'checkIn' : Time, 'checkOut' : Time });
  const ComparisonInput = IDL.Record({
    'ticketSources' : IDL.Vec(Ticket),
    'event' : IDL.Text,
    'userChoice' : IDL.Opt(BundleInput),
    'vipPackageOptions' : IDL.Vec(VIPPackage),
    'hotels' : IDL.Vec(Hotel),
    'travelWindow' : TravelWindow,
  });
  const Bundle = IDL.Record({
    'ticket' : Ticket,
    'hotel' : Hotel,
    'roomType' : RoomType,
  });
  const TripComparison = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'upgradeAlternatives' : IDL.Vec(Bundle),
    'ticketSources' : IDL.Vec(Ticket),
    'event' : IDL.Text,
    'userChoice' : IDL.Opt(Bundle),
    'vipPackageOptions' : IDL.Vec(VIPPackage),
    'hotels' : IDL.Vec(Hotel),
    'travelWindow' : TravelWindow,
    'foundVIPPackage' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'parentPermissionConfirmed' : IDL.Bool,
    'friends' : IDL.Vec(FriendEntry),
  });
  const PhotoInput = IDL.Record({
    'externalBlob' : ExternalBlob,
    'tags' : IDL.Vec(PhotoTag),
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFriendRequest' : IDL.Func([FriendEntry], [], []),
    'addGroupMessage' : IDL.Func([IDL.Nat, NewMessage], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlbum' : IDL.Func([IDL.Text], [Album], []),
    'createGroup' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Vec(GroupMember), IDL.Opt(IDL.Nat)],
        [Group],
        [],
      ),
    'createTripComparison' : IDL.Func(
        [ComparisonInput, IDL.Bool],
        [TripComparison],
        [],
      ),
    'deleteAlbum' : IDL.Func([IDL.Nat], [], []),
    'deleteComparison' : IDL.Func([IDL.Nat], [], []),
    'deletePhotoFromAlbum' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAlbum' : IDL.Func([IDL.Nat], [IDL.Opt(Album)], ['query']),
    'getAllAlbums' : IDL.Func([IDL.Principal], [IDL.Vec(Album)], ['query']),
    'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getAllUserComparisons' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TripComparison)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGroup' : IDL.Func([IDL.Nat], [IDL.Opt(Group)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveGroup' : IDL.Func([IDL.Nat], [], []),
    'removeFriend' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setParentPermissionStatus' : IDL.Func([IDL.Bool], [], []),
    'uploadPhotoToAlbum' : IDL.Func([IDL.Nat, PhotoInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };