/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GeoLocation {
    latitude: number;
    longitude: number;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Amenity {
    name: string;
    description?: string;
    category: AmenityCategory;
}
export interface Group {
    id: bigint;
    creator: Principal;
    members: Array<GroupMember>;
    comparisonId?: bigint;
    messages: Array<Message>;
    createdAt: Time;
    lastUpdate: Time;
    groupName: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Album {
    id: bigint;
    title: string;
    creator: Principal;
    isShared: boolean;
    photos: Array<Photo>;
}
export interface NewMessage {
    content: string;
    author?: GroupMember;
}
export interface PriceRange {
    maxPrice: number;
    currency: string;
    minPrice: number;
    rateType: PriceType;
}
export interface Hotel {
    roomTypes: Array<RoomType>;
    starRating?: number;
    country: string;
    reviews?: number;
    imageUrls?: Array<string>;
    city: string;
    name: string;
    checkInTime?: string;
    amenities: Array<Amenity>;
    state?: string;
    address: string;
    prices?: PriceRange;
    brand?: string;
    checkOutTime?: string;
    location?: GeoLocation;
}
export interface VIPPackage {
    id: bigint;
    exclusivePerks?: string;
    name: string;
    inclusions: Array<string>;
    currency: string;
    price: number;
}
export interface Photo {
    id: bigint;
    externalBlob: ExternalBlob;
    createdAt: Time;
    createdBy: Principal;
    tags: Array<PhotoTag>;
    description: string;
    imageUrl: string;
}
export interface ComparisonInput {
    ticketSources: Array<Ticket>;
    event: string;
    userChoice?: BundleInput;
    vipPackageOptions: Array<VIPPackage>;
    hotels: Array<Hotel>;
    travelWindow: TravelWindow;
}
export interface BundleInput {
    ticket: Ticket;
    hotel: Hotel;
    roomType: RoomType;
}
export interface GroupMember {
    id: bigint;
    userName: string;
    principal: Principal;
    isConfirmed: boolean;
}
export interface Bundle {
    ticket: Ticket;
    hotel: Hotel;
    roomType: RoomType;
}
export interface TripComparison {
    id: bigint;
    userId: Principal;
    createdAt: Time;
    upgradeAlternatives: Array<Bundle>;
    ticketSources: Array<Ticket>;
    event: string;
    userChoice?: Bundle;
    vipPackageOptions: Array<VIPPackage>;
    hotels: Array<Hotel>;
    travelWindow: TravelWindow;
    foundVIPPackage: boolean;
}
export interface RoomType {
    bedType?: string;
    occupancy?: bigint;
    views?: string;
    cancellationPolicy?: string;
    name: string;
    size?: bigint;
    description?: string;
    amenities: Array<Amenity>;
    price: number;
}
export interface PhotoTag {
    principal: Principal;
    displayName: string;
    position: [number, number];
}
export interface TravelWindow {
    checkIn: Time;
    checkOut: Time;
}
export interface FriendEntry {
    id: bigint;
    principal: Principal;
    name?: string;
    isConfirmed: boolean;
}
export interface PhotoInput {
    externalBlob: ExternalBlob;
    tags: Array<PhotoTag>;
    description: string;
    imageUrl: string;
}
export interface Message {
    id: bigint;
    content: string;
    author?: GroupMember;
    timestamp: Time;
}
export interface Ticket {
    id: bigint;
    name: string;
    type: TicketType;
    available: boolean;
    currency: string;
    price: number;
}
export interface UserProfile {
    name: string;
    parentPermissionConfirmed: boolean;
    friends: Array<FriendEntry>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AmenityCategory {
    transportation = "transportation",
    safetyAndSecurity = "safetyAndSecurity",
    entertainment = "entertainment",
    roomFeatures = "roomFeatures",
    recreationalFacilities = "recreationalFacilities",
    businessServices = "businessServices",
    petFriendly = "petFriendly",
    accessibilityFeatures = "accessibilityFeatures",
    technology = "technology",
    diningOptions = "diningOptions",
    hotelServices = "hotelServices",
    hospitalityServices = "hospitalityServices",
    wellnessAndSpa = "wellnessAndSpa"
}
export enum PriceType {
    perNight = "perNight",
    perWeek = "perWeek",
    perMonth = "perMonth"
}
export enum TicketType {
    vip = "vip",
    standard = "standard"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFriendRequest(friendEntry: FriendEntry): Promise<void>;
    addGroupMessage(groupId: bigint, message: NewMessage): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAlbum(title: string): Promise<Album>;
    createGroup(groupName: string, creator: Principal, members: Array<GroupMember>, comparisonId: bigint | null): Promise<Group>;
    createTripComparison(input: ComparisonInput, foundVIPPackage: boolean): Promise<TripComparison>;
    deleteAlbum(albumId: bigint): Promise<void>;
    deleteComparison(id: bigint): Promise<void>;
    deletePhotoFromAlbum(albumId: bigint, photoId: bigint): Promise<void>;
    getAlbum(albumId: bigint): Promise<Album | null>;
    getAllAlbums(userId: Principal): Promise<Array<Album>>;
    getAllGroups(): Promise<Array<Group>>;
    getAllUserComparisons(userId: Principal): Promise<Array<TripComparison>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGroup(groupId: bigint): Promise<Group | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    leaveGroup(groupId: bigint): Promise<void>;
    removeFriend(friendId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setParentPermissionStatus(hasPermission: boolean): Promise<void>;
    uploadPhotoToAlbum(albumId: bigint, photo: PhotoInput): Promise<void>;
}
import type { Album as _Album, Amenity as _Amenity, AmenityCategory as _AmenityCategory, Bundle as _Bundle, BundleInput as _BundleInput, ComparisonInput as _ComparisonInput, ExternalBlob as _ExternalBlob, FriendEntry as _FriendEntry, GeoLocation as _GeoLocation, Group as _Group, GroupMember as _GroupMember, Hotel as _Hotel, Message as _Message, NewMessage as _NewMessage, Photo as _Photo, PhotoInput as _PhotoInput, PhotoTag as _PhotoTag, PriceRange as _PriceRange, PriceType as _PriceType, RoomType as _RoomType, Ticket as _Ticket, TicketType as _TicketType, Time as _Time, TravelWindow as _TravelWindow, TripComparison as _TripComparison, UserProfile as _UserProfile, UserRole as _UserRole, VIPPackage as _VIPPackage, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFriendRequest(arg0: FriendEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFriendRequest(to_candid_FriendEntry_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFriendRequest(to_candid_FriendEntry_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addGroupMessage(arg0: bigint, arg1: NewMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGroupMessage(arg0, to_candid_NewMessage_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGroupMessage(arg0, to_candid_NewMessage_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAlbum(arg0: string): Promise<Album> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlbum(arg0);
                return from_candid_Album_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlbum(arg0);
            return from_candid_Album_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGroup(arg0: string, arg1: Principal, arg2: Array<GroupMember>, arg3: bigint | null): Promise<Group> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Group_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, arg1, arg2, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Group_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTripComparison(arg0: ComparisonInput, arg1: boolean): Promise<TripComparison> {
        if (this.processError) {
            try {
                const result = await this.actor.createTripComparison(to_candid_ComparisonInput_n27(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_TripComparison_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTripComparison(to_candid_ComparisonInput_n27(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_TripComparison_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAlbum(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlbum(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlbum(arg0);
            return result;
        }
    }
    async deleteComparison(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComparison(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComparison(arg0);
            return result;
        }
    }
    async deletePhotoFromAlbum(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhotoFromAlbum(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhotoFromAlbum(arg0, arg1);
            return result;
        }
    }
    async getAlbum(arg0: bigint): Promise<Album | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlbum(arg0);
                return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlbum(arg0);
            return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAlbums(arg0: Principal): Promise<Array<Album>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlbums(arg0);
                return from_candid_vec_n89(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlbums(arg0);
            return from_candid_vec_n89(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGroups(): Promise<Array<Group>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGroups();
                return from_candid_vec_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGroups();
            return from_candid_vec_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserComparisons(arg0: Principal): Promise<Array<TripComparison>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserComparisons(arg0);
                return from_candid_vec_n91(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserComparisons(arg0);
            return from_candid_vec_n91(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n92(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n92(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n98(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n98(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroup(arg0: bigint): Promise<Group | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroup(arg0);
                return from_candid_opt_n100(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroup(arg0);
            return from_candid_opt_n100(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n92(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n92(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async leaveGroup(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return result;
        }
    }
    async removeFriend(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFriend(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n101(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n101(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setParentPermissionStatus(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setParentPermissionStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setParentPermissionStatus(arg0);
            return result;
        }
    }
    async uploadPhotoToAlbum(arg0: bigint, arg1: PhotoInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhotoToAlbum(arg0, await to_candid_PhotoInput_n104(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhotoToAlbum(arg0, await to_candid_PhotoInput_n104(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_Album_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Album): Promise<Album> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_AmenityCategory_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AmenityCategory): AmenityCategory {
    return from_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function from_candid_Amenity_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Amenity): Amenity {
    return from_candid_record_n71(_uploadFile, _downloadFile, value);
}
function from_candid_Bundle_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bundle): Bundle {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FriendEntry_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendEntry): FriendEntry {
    return from_candid_record_n97(_uploadFile, _downloadFile, value);
}
function from_candid_Group_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Group): Group {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Hotel_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Hotel): Hotel {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_Photo_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Photo): Promise<Photo> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PriceRange_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceRange): PriceRange {
    return from_candid_record_n78(_uploadFile, _downloadFile, value);
}
function from_candid_PriceType_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceType): PriceType {
    return from_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_record_n67(_uploadFile, _downloadFile, value);
}
function from_candid_TicketType_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketType): TicketType {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Ticket_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_TripComparison_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripComparison): TripComparison {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n94(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n99(_uploadFile, _downloadFile, value);
}
function from_candid_VIPPackage_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VIPPackage): VIPPackage {
    return from_candid_record_n86(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Group]): Group | null {
    return value.length === 0 ? null : from_candid_Group_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GroupMember]): GroupMember | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PriceRange]): PriceRange | null {
    return value.length === 0 ? null : from_candid_PriceRange_n77(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeoLocation]): GeoLocation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Bundle]): Bundle | null {
    return value.length === 0 ? null : from_candid_Bundle_n57(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Album]): Promise<Album | null> {
    return value.length === 0 ? null : await from_candid_Album_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n93(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    creator: Principal;
    isShared: boolean;
    photos: Array<_Photo>;
}): Promise<{
    id: bigint;
    title: string;
    creator: Principal;
    isShared: boolean;
    photos: Array<Photo>;
}> {
    return {
        id: value.id,
        title: value.title,
        creator: value.creator,
        isShared: value.isShared,
        photos: await from_candid_vec_n16(_uploadFile, _downloadFile, value.photos)
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    externalBlob: _ExternalBlob;
    createdAt: _Time;
    createdBy: Principal;
    tags: Array<_PhotoTag>;
    description: string;
    imageUrl: string;
}): Promise<{
    id: bigint;
    externalBlob: ExternalBlob;
    createdAt: Time;
    createdBy: Principal;
    tags: Array<PhotoTag>;
    description: string;
    imageUrl: string;
}> {
    return {
        id: value.id,
        externalBlob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.externalBlob),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        tags: value.tags,
        description: value.description,
        imageUrl: value.imageUrl
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    creator: Principal;
    members: Array<_GroupMember>;
    comparisonId: [] | [bigint];
    messages: Array<_Message>;
    createdAt: _Time;
    lastUpdate: _Time;
    groupName: string;
}): {
    id: bigint;
    creator: Principal;
    members: Array<GroupMember>;
    comparisonId?: bigint;
    messages: Array<Message>;
    createdAt: Time;
    lastUpdate: Time;
    groupName: string;
} {
    return {
        id: value.id,
        creator: value.creator,
        members: value.members,
        comparisonId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.comparisonId)),
        messages: from_candid_vec_n23(_uploadFile, _downloadFile, value.messages),
        createdAt: value.createdAt,
        lastUpdate: value.lastUpdate,
        groupName: value.groupName
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    author: [] | [_GroupMember];
    timestamp: _Time;
}): {
    id: bigint;
    content: string;
    author?: GroupMember;
    timestamp: Time;
} {
    return {
        id: value.id,
        content: value.content,
        author: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.author)),
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: Principal;
    createdAt: _Time;
    upgradeAlternatives: Array<_Bundle>;
    ticketSources: Array<_Ticket>;
    event: string;
    userChoice: [] | [_Bundle];
    vipPackageOptions: Array<_VIPPackage>;
    hotels: Array<_Hotel>;
    travelWindow: _TravelWindow;
    foundVIPPackage: boolean;
}): {
    id: bigint;
    userId: Principal;
    createdAt: Time;
    upgradeAlternatives: Array<Bundle>;
    ticketSources: Array<Ticket>;
    event: string;
    userChoice?: Bundle;
    vipPackageOptions: Array<VIPPackage>;
    hotels: Array<Hotel>;
    travelWindow: TravelWindow;
    foundVIPPackage: boolean;
} {
    return {
        id: value.id,
        userId: value.userId,
        createdAt: value.createdAt,
        upgradeAlternatives: from_candid_vec_n56(_uploadFile, _downloadFile, value.upgradeAlternatives),
        ticketSources: from_candid_vec_n82(_uploadFile, _downloadFile, value.ticketSources),
        event: value.event,
        userChoice: record_opt_to_undefined(from_candid_opt_n83(_uploadFile, _downloadFile, value.userChoice)),
        vipPackageOptions: from_candid_vec_n84(_uploadFile, _downloadFile, value.vipPackageOptions),
        hotels: from_candid_vec_n87(_uploadFile, _downloadFile, value.hotels),
        travelWindow: value.travelWindow,
        foundVIPPackage: value.foundVIPPackage
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticket: _Ticket;
    hotel: _Hotel;
    roomType: _RoomType;
}): {
    ticket: Ticket;
    hotel: Hotel;
    roomType: RoomType;
} {
    return {
        ticket: from_candid_Ticket_n59(_uploadFile, _downloadFile, value.ticket),
        hotel: from_candid_Hotel_n63(_uploadFile, _downloadFile, value.hotel),
        roomType: from_candid_RoomType_n66(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    type: _TicketType;
    available: boolean;
    currency: string;
    price: number;
}): {
    id: bigint;
    name: string;
    type: TicketType;
    available: boolean;
    currency: string;
    price: number;
} {
    return {
        id: value.id,
        name: value.name,
        type: from_candid_TicketType_n61(_uploadFile, _downloadFile, value.type),
        available: value.available,
        currency: value.currency,
        price: value.price
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roomTypes: Array<_RoomType>;
    starRating: [] | [number];
    country: string;
    reviews: [] | [number];
    imageUrls: [] | [Array<string>];
    city: string;
    name: string;
    checkInTime: [] | [string];
    amenities: Array<_Amenity>;
    state: [] | [string];
    address: string;
    prices: [] | [_PriceRange];
    brand: [] | [string];
    checkOutTime: [] | [string];
    location: [] | [_GeoLocation];
}): {
    roomTypes: Array<RoomType>;
    starRating?: number;
    country: string;
    reviews?: number;
    imageUrls?: Array<string>;
    city: string;
    name: string;
    checkInTime?: string;
    amenities: Array<Amenity>;
    state?: string;
    address: string;
    prices?: PriceRange;
    brand?: string;
    checkOutTime?: string;
    location?: GeoLocation;
} {
    return {
        roomTypes: from_candid_vec_n65(_uploadFile, _downloadFile, value.roomTypes),
        starRating: record_opt_to_undefined(from_candid_opt_n74(_uploadFile, _downloadFile, value.starRating)),
        country: value.country,
        reviews: record_opt_to_undefined(from_candid_opt_n74(_uploadFile, _downloadFile, value.reviews)),
        imageUrls: record_opt_to_undefined(from_candid_opt_n75(_uploadFile, _downloadFile, value.imageUrls)),
        city: value.city,
        name: value.name,
        checkInTime: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.checkInTime)),
        amenities: from_candid_vec_n69(_uploadFile, _downloadFile, value.amenities),
        state: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.state)),
        address: value.address,
        prices: record_opt_to_undefined(from_candid_opt_n76(_uploadFile, _downloadFile, value.prices)),
        brand: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.brand)),
        checkOutTime: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.checkOutTime)),
        location: record_opt_to_undefined(from_candid_opt_n81(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bedType: [] | [string];
    occupancy: [] | [bigint];
    views: [] | [string];
    cancellationPolicy: [] | [string];
    name: string;
    size: [] | [bigint];
    description: [] | [string];
    amenities: Array<_Amenity>;
    price: number;
}): {
    bedType?: string;
    occupancy?: bigint;
    views?: string;
    cancellationPolicy?: string;
    name: string;
    size?: bigint;
    description?: string;
    amenities: Array<Amenity>;
    price: number;
} {
    return {
        bedType: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.bedType)),
        occupancy: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.occupancy)),
        views: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.views)),
        cancellationPolicy: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.cancellationPolicy)),
        name: value.name,
        size: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.size)),
        description: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.description)),
        amenities: from_candid_vec_n69(_uploadFile, _downloadFile, value.amenities),
        price: value.price
    };
}
function from_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: [] | [string];
    category: _AmenityCategory;
}): {
    name: string;
    description?: string;
    category: AmenityCategory;
} {
    return {
        name: value.name,
        description: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.description)),
        category: from_candid_AmenityCategory_n72(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxPrice: number;
    currency: string;
    minPrice: number;
    rateType: _PriceType;
}): {
    maxPrice: number;
    currency: string;
    minPrice: number;
    rateType: PriceType;
} {
    return {
        maxPrice: value.maxPrice,
        currency: value.currency,
        minPrice: value.minPrice,
        rateType: from_candid_PriceType_n79(_uploadFile, _downloadFile, value.rateType)
    };
}
function from_candid_record_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    exclusivePerks: [] | [string];
    name: string;
    inclusions: Array<string>;
    currency: string;
    price: number;
}): {
    id: bigint;
    exclusivePerks?: string;
    name: string;
    inclusions: Array<string>;
    currency: string;
    price: number;
} {
    return {
        id: value.id,
        exclusivePerks: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.exclusivePerks)),
        name: value.name,
        inclusions: value.inclusions,
        currency: value.currency,
        price: value.price
    };
}
function from_candid_record_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    parentPermissionConfirmed: boolean;
    friends: Array<_FriendEntry>;
}): {
    name: string;
    parentPermissionConfirmed: boolean;
    friends: Array<FriendEntry>;
} {
    return {
        name: value.name,
        parentPermissionConfirmed: value.parentPermissionConfirmed,
        friends: from_candid_vec_n95(_uploadFile, _downloadFile, value.friends)
    };
}
function from_candid_record_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: Principal;
    name: [] | [string];
    isConfirmed: boolean;
}): {
    id: bigint;
    principal: Principal;
    name?: string;
    isConfirmed: boolean;
} {
    return {
        id: value.id,
        principal: value.principal,
        name: record_opt_to_undefined(from_candid_opt_n68(_uploadFile, _downloadFile, value.name)),
        isConfirmed: value.isConfirmed
    };
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vip: null;
} | {
    standard: null;
}): TicketType {
    return "vip" in value ? TicketType.vip : "standard" in value ? TicketType.standard : value;
}
function from_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transportation: null;
} | {
    safetyAndSecurity: null;
} | {
    entertainment: null;
} | {
    roomFeatures: null;
} | {
    recreationalFacilities: null;
} | {
    businessServices: null;
} | {
    petFriendly: null;
} | {
    accessibilityFeatures: null;
} | {
    technology: null;
} | {
    diningOptions: null;
} | {
    hotelServices: null;
} | {
    hospitalityServices: null;
} | {
    wellnessAndSpa: null;
}): AmenityCategory {
    return "transportation" in value ? AmenityCategory.transportation : "safetyAndSecurity" in value ? AmenityCategory.safetyAndSecurity : "entertainment" in value ? AmenityCategory.entertainment : "roomFeatures" in value ? AmenityCategory.roomFeatures : "recreationalFacilities" in value ? AmenityCategory.recreationalFacilities : "businessServices" in value ? AmenityCategory.businessServices : "petFriendly" in value ? AmenityCategory.petFriendly : "accessibilityFeatures" in value ? AmenityCategory.accessibilityFeatures : "technology" in value ? AmenityCategory.technology : "diningOptions" in value ? AmenityCategory.diningOptions : "hotelServices" in value ? AmenityCategory.hotelServices : "hospitalityServices" in value ? AmenityCategory.hospitalityServices : "wellnessAndSpa" in value ? AmenityCategory.wellnessAndSpa : value;
}
function from_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    perNight: null;
} | {
    perWeek: null;
} | {
    perMonth: null;
}): PriceType {
    return "perNight" in value ? PriceType.perNight : "perWeek" in value ? PriceType.perWeek : "perMonth" in value ? PriceType.perMonth : value;
}
function from_candid_variant_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Photo>): Promise<Array<Photo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Photo_n17(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bundle>): Array<Bundle> {
    return value.map((x)=>from_candid_Bundle_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoomType>): Array<RoomType> {
    return value.map((x)=>from_candid_RoomType_n66(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Amenity>): Array<Amenity> {
    return value.map((x)=>from_candid_Amenity_n70(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Array<Ticket> {
    return value.map((x)=>from_candid_Ticket_n59(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VIPPackage>): Array<VIPPackage> {
    return value.map((x)=>from_candid_VIPPackage_n85(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Hotel>): Array<Hotel> {
    return value.map((x)=>from_candid_Hotel_n63(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Album>): Promise<Array<Album>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Album_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Group>): Array<Group> {
    return value.map((x)=>from_candid_Group_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TripComparison>): Array<TripComparison> {
    return value.map((x)=>from_candid_TripComparison_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendEntry>): Array<FriendEntry> {
    return value.map((x)=>from_candid_FriendEntry_n96(_uploadFile, _downloadFile, x));
}
function to_candid_AmenityCategory_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AmenityCategory): _AmenityCategory {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_Amenity_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Amenity): _Amenity {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_BundleInput_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BundleInput): _BundleInput {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_ComparisonInput_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ComparisonInput): _ComparisonInput {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n106(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FriendEntry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FriendEntry): _FriendEntry {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Hotel_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Hotel): _Hotel {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_NewMessage_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewMessage): _NewMessage {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_PhotoInput_n104(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhotoInput): Promise<_PhotoInput> {
    return await to_candid_record_n105(_uploadFile, _downloadFile, value);
}
function to_candid_PriceRange_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceRange): _PriceRange {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_PriceType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceType): _PriceType {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_RoomType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_TicketType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketType): _TicketType {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_Ticket_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Ticket): _Ticket {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n102(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_VIPPackage_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VIPPackage): _VIPPackage {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    parentPermissionConfirmed: boolean;
    friends: Array<FriendEntry>;
}): {
    name: string;
    parentPermissionConfirmed: boolean;
    friends: Array<_FriendEntry>;
} {
    return {
        name: value.name,
        parentPermissionConfirmed: value.parentPermissionConfirmed,
        friends: to_candid_vec_n103(_uploadFile, _downloadFile, value.friends)
    };
}
async function to_candid_record_n105(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    externalBlob: ExternalBlob;
    tags: Array<PhotoTag>;
    description: string;
    imageUrl: string;
}): Promise<{
    externalBlob: _ExternalBlob;
    tags: Array<_PhotoTag>;
    description: string;
    imageUrl: string;
}> {
    return {
        externalBlob: await to_candid_ExternalBlob_n106(_uploadFile, _downloadFile, value.externalBlob),
        tags: value.tags,
        description: value.description,
        imageUrl: value.imageUrl
    };
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    author?: GroupMember;
}): {
    content: string;
    author: [] | [_GroupMember];
} {
    return {
        content: value.content,
        author: value.author ? candid_some(value.author) : candid_none()
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticketSources: Array<Ticket>;
    event: string;
    userChoice?: BundleInput;
    vipPackageOptions: Array<VIPPackage>;
    hotels: Array<Hotel>;
    travelWindow: TravelWindow;
}): {
    ticketSources: Array<_Ticket>;
    event: string;
    userChoice: [] | [_BundleInput];
    vipPackageOptions: Array<_VIPPackage>;
    hotels: Array<_Hotel>;
    travelWindow: _TravelWindow;
} {
    return {
        ticketSources: to_candid_vec_n29(_uploadFile, _downloadFile, value.ticketSources),
        event: value.event,
        userChoice: value.userChoice ? candid_some(to_candid_BundleInput_n34(_uploadFile, _downloadFile, value.userChoice)) : candid_none(),
        vipPackageOptions: to_candid_vec_n50(_uploadFile, _downloadFile, value.vipPackageOptions),
        hotels: to_candid_vec_n53(_uploadFile, _downloadFile, value.hotels),
        travelWindow: value.travelWindow
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    type: TicketType;
    available: boolean;
    currency: string;
    price: number;
}): {
    id: bigint;
    name: string;
    type: _TicketType;
    available: boolean;
    currency: string;
    price: number;
} {
    return {
        id: value.id,
        name: value.name,
        type: to_candid_TicketType_n32(_uploadFile, _downloadFile, value.type),
        available: value.available,
        currency: value.currency,
        price: value.price
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ticket: Ticket;
    hotel: Hotel;
    roomType: RoomType;
}): {
    ticket: _Ticket;
    hotel: _Hotel;
    roomType: _RoomType;
} {
    return {
        ticket: to_candid_Ticket_n30(_uploadFile, _downloadFile, value.ticket),
        hotel: to_candid_Hotel_n36(_uploadFile, _downloadFile, value.hotel),
        roomType: to_candid_RoomType_n39(_uploadFile, _downloadFile, value.roomType)
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roomTypes: Array<RoomType>;
    starRating?: number;
    country: string;
    reviews?: number;
    imageUrls?: Array<string>;
    city: string;
    name: string;
    checkInTime?: string;
    amenities: Array<Amenity>;
    state?: string;
    address: string;
    prices?: PriceRange;
    brand?: string;
    checkOutTime?: string;
    location?: GeoLocation;
}): {
    roomTypes: Array<_RoomType>;
    starRating: [] | [number];
    country: string;
    reviews: [] | [number];
    imageUrls: [] | [Array<string>];
    city: string;
    name: string;
    checkInTime: [] | [string];
    amenities: Array<_Amenity>;
    state: [] | [string];
    address: string;
    prices: [] | [_PriceRange];
    brand: [] | [string];
    checkOutTime: [] | [string];
    location: [] | [_GeoLocation];
} {
    return {
        roomTypes: to_candid_vec_n38(_uploadFile, _downloadFile, value.roomTypes),
        starRating: value.starRating ? candid_some(value.starRating) : candid_none(),
        country: value.country,
        reviews: value.reviews ? candid_some(value.reviews) : candid_none(),
        imageUrls: value.imageUrls ? candid_some(value.imageUrls) : candid_none(),
        city: value.city,
        name: value.name,
        checkInTime: value.checkInTime ? candid_some(value.checkInTime) : candid_none(),
        amenities: to_candid_vec_n41(_uploadFile, _downloadFile, value.amenities),
        state: value.state ? candid_some(value.state) : candid_none(),
        address: value.address,
        prices: value.prices ? candid_some(to_candid_PriceRange_n46(_uploadFile, _downloadFile, value.prices)) : candid_none(),
        brand: value.brand ? candid_some(value.brand) : candid_none(),
        checkOutTime: value.checkOutTime ? candid_some(value.checkOutTime) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bedType?: string;
    occupancy?: bigint;
    views?: string;
    cancellationPolicy?: string;
    name: string;
    size?: bigint;
    description?: string;
    amenities: Array<Amenity>;
    price: number;
}): {
    bedType: [] | [string];
    occupancy: [] | [bigint];
    views: [] | [string];
    cancellationPolicy: [] | [string];
    name: string;
    size: [] | [bigint];
    description: [] | [string];
    amenities: Array<_Amenity>;
    price: number;
} {
    return {
        bedType: value.bedType ? candid_some(value.bedType) : candid_none(),
        occupancy: value.occupancy ? candid_some(value.occupancy) : candid_none(),
        views: value.views ? candid_some(value.views) : candid_none(),
        cancellationPolicy: value.cancellationPolicy ? candid_some(value.cancellationPolicy) : candid_none(),
        name: value.name,
        size: value.size ? candid_some(value.size) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        amenities: to_candid_vec_n41(_uploadFile, _downloadFile, value.amenities),
        price: value.price
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description?: string;
    category: AmenityCategory;
}): {
    name: string;
    description: [] | [string];
    category: _AmenityCategory;
} {
    return {
        name: value.name,
        description: value.description ? candid_some(value.description) : candid_none(),
        category: to_candid_AmenityCategory_n44(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maxPrice: number;
    currency: string;
    minPrice: number;
    rateType: PriceType;
}): {
    maxPrice: number;
    currency: string;
    minPrice: number;
    rateType: _PriceType;
} {
    return {
        maxPrice: value.maxPrice,
        currency: value.currency,
        minPrice: value.minPrice,
        rateType: to_candid_PriceType_n48(_uploadFile, _downloadFile, value.rateType)
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    exclusivePerks?: string;
    name: string;
    inclusions: Array<string>;
    currency: string;
    price: number;
}): {
    id: bigint;
    exclusivePerks: [] | [string];
    name: string;
    inclusions: Array<string>;
    currency: string;
    price: number;
} {
    return {
        id: value.id,
        exclusivePerks: value.exclusivePerks ? candid_some(value.exclusivePerks) : candid_none(),
        name: value.name,
        inclusions: value.inclusions,
        currency: value.currency,
        price: value.price
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    principal: Principal;
    name?: string;
    isConfirmed: boolean;
}): {
    id: bigint;
    principal: Principal;
    name: [] | [string];
    isConfirmed: boolean;
} {
    return {
        id: value.id,
        principal: value.principal,
        name: value.name ? candid_some(value.name) : candid_none(),
        isConfirmed: value.isConfirmed
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketType): {
    vip: null;
} | {
    standard: null;
} {
    return value == TicketType.vip ? {
        vip: null
    } : value == TicketType.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AmenityCategory): {
    transportation: null;
} | {
    safetyAndSecurity: null;
} | {
    entertainment: null;
} | {
    roomFeatures: null;
} | {
    recreationalFacilities: null;
} | {
    businessServices: null;
} | {
    petFriendly: null;
} | {
    accessibilityFeatures: null;
} | {
    technology: null;
} | {
    diningOptions: null;
} | {
    hotelServices: null;
} | {
    hospitalityServices: null;
} | {
    wellnessAndSpa: null;
} {
    return value == AmenityCategory.transportation ? {
        transportation: null
    } : value == AmenityCategory.safetyAndSecurity ? {
        safetyAndSecurity: null
    } : value == AmenityCategory.entertainment ? {
        entertainment: null
    } : value == AmenityCategory.roomFeatures ? {
        roomFeatures: null
    } : value == AmenityCategory.recreationalFacilities ? {
        recreationalFacilities: null
    } : value == AmenityCategory.businessServices ? {
        businessServices: null
    } : value == AmenityCategory.petFriendly ? {
        petFriendly: null
    } : value == AmenityCategory.accessibilityFeatures ? {
        accessibilityFeatures: null
    } : value == AmenityCategory.technology ? {
        technology: null
    } : value == AmenityCategory.diningOptions ? {
        diningOptions: null
    } : value == AmenityCategory.hotelServices ? {
        hotelServices: null
    } : value == AmenityCategory.hospitalityServices ? {
        hospitalityServices: null
    } : value == AmenityCategory.wellnessAndSpa ? {
        wellnessAndSpa: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceType): {
    perNight: null;
} | {
    perWeek: null;
} | {
    perMonth: null;
} {
    return value == PriceType.perNight ? {
        perNight: null
    } : value == PriceType.perWeek ? {
        perWeek: null
    } : value == PriceType.perMonth ? {
        perMonth: null
    } : value;
}
function to_candid_vec_n103(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FriendEntry>): Array<_FriendEntry> {
    return value.map((x)=>to_candid_FriendEntry_n8(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Ticket>): Array<_Ticket> {
    return value.map((x)=>to_candid_Ticket_n30(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RoomType>): Array<_RoomType> {
    return value.map((x)=>to_candid_RoomType_n39(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Amenity>): Array<_Amenity> {
    return value.map((x)=>to_candid_Amenity_n42(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<VIPPackage>): Array<_VIPPackage> {
    return value.map((x)=>to_candid_VIPPackage_n51(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Hotel>): Array<_Hotel> {
    return value.map((x)=>to_candid_Hotel_n36(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
